<a href="https://colab.research.google.com/github/iqbalafreen/iqbal/blob/main/iqbal_day1%2Cipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello,world!")
if 5 > 2:
  print("five is greater than two!")
  a=5
  b=("hello,world")
  a=5
  z="john"
  print(a)
  print(z)
  x=3
  print(type(x))
  y='4'
  print(type(y))
  z=8.0
  print(type(z))


**SETS**

In [ ]:
my_set={"cherry","mango","banana"}
print(my_set)

{'banana', 'mango', 'cherry'}


**dict**

In [ ]:
a_dict={"math":60,
        "science":70,
        "electronics":45,
}
print(a_dict)
a_dict["electronics"]=75

{'math': 60, 'science': 70, 'electronics': 45}


**else if**

In [ ]:
# a=22
# b=22
# if b > a:
#    print("b is greater than a")
# elif a==b:
#     print("a is greater than b")
a=int(input("enter the value of a:"))
b=int(input("enter the vale of b:"))
if b>a:
  print("b is greater than a")
elif a==b:
  print("a is greater than b")

enter the value of a:22
enter the vale of b:23
b is greater than a


**if**

In [ ]:
a=100
b=60
if a > b or b == a:
  print("both the condition are true")

both the condition are true


In [ ]:
u=100
t=300
e=500
if u > t and e > t:
  print("both conditions are true")

**while**

In [ ]:
i=1
while i < 10:
  print(i)
  i +=1


  if i == 5:
    break



1
2
3
4


**while continue**

In [ ]:
i = 0
while i < 6:
  i += 1
  if i == 3:
    continue
  print(i)

1
2
4
5
6


In [ ]:
i = 1
while i < 6:
  print(i)
  i +=1
else:
    print("1 is no longer than 6")

1
2
3
4
5
1 is no longer than 6


**for**

In [ ]:
my_list=["abc","def","ghi",True,9.7,'c',123]
for x in my_list:
 print(x)
 if x=="ghi":
  break

abc
def
ghi


**function**

In [ ]:
def my_function(*heights):
  print("the last height entered is" + str(heights[2]))

my_function(8,6,90,50)

the last height entered is90


In [ ]:
def my_function():
  print("bye")

my_function()

bye


In [ ]:
def my_funct(fname, lname, email):
  print(fname+ " " +lname+ " "+email)

my_funct("ifra","iqbal","nabiha")
my_funct(fname="iqbal",lname="ifra",email="nabiha")

ifra iqbal nabiha
iqbal ifra nabiha


In [ ]:
def my_function(square):
  print(square * square)
my_function(2)
my_function(4)
my_function(6)

4
16
36


In [ ]:
def sq_function(z):
  return z**2

print(sq_function(2))
print(sq_function(6))

4
36


In [ ]:
def mult(n):
  for i in range(1,11):
    print(n ,"x",i,"=",n*i)


mult(9)

9 x 1 = 9
9 x 2 = 18
9 x 3 = 27
9 x 4 = 36
9 x 5 = 45
9 x 6 = 54
9 x 7 = 63
9 x 8 = 72
9 x 9 = 81
9 x 10 = 90


In [ ]:
x = lambda a, b : a * b
print(x(2,4))

8


In [ ]:
def my_function(n):
  return lambda a : a*n

mult=my_function(3)

print(mult(100))

300


password strength

In [ ]:
def printstrongness (input_string):

  n= len (input_string)

  haslower = False
  hasupper = False
  hasdigit = False
  specialchar = False
  normalchar = ["a-z A-Z"]
  for i in range(n):
    if input_string[i] . islower():
      haslower = True
    if input_string[i] . isupper():
      hasupper = True
    if input_string[i] . isdigit():
      hasdigit =  True
    if input_string[i] not in normalchars:
      specialchar = True
      print("strength of password:-", end =" ")
    if(haslower and hasupper and specialchar and n>8):
        print("strong")
    elif ((haslower and hasupper) and specialchar and n>=6):
      print("moderate")
    elif:
      print("weak"):
if__name__=="__main__":
  input_string = "greeksforgreeks!@12"
printStrongness(input_string)

SyntaxError: ignored

In [ ]:
my_list = [1,2,3,4]
new_list = [x for x in my_list if x % 2==0]
print(new_list)

[2, 4]


In [ ]:
new_list = [x for x in my_list if x !=3]
print(new_list)

[1, 2, 4]


In [ ]:
my_list=[x for x in range(1,11)]
print(my_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
my_list=[x for x in range(21) if x>10]
print(my_list)

[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [ ]:
def pypart(n):
  for i in range(0,n):
    for j in range(0,i+1):
      print(" * ",end="")
    print("\r")
n=5
pypart(n)

 * 
 *  * 
 *  *  * 
 *  *  *  * 
 *  *  *  *  * 


**numpy**

In [ ]:
import numpy as np

arr=np.array((1,2,3,4,5))

print(arr)

[1 2 3 4 5]


In [ ]:
import numpy as np
my_array=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_arr=my_array.reshape(3,2,2)
print(new_arr)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


**pandas**

In [ ]:
import pandas as pd
a=[2,4,3,5,6]
myvar=pd.Series(a)
print(myvar)

0    2
1    4
2    3
3    5
4    6
dtype: int64


In [ ]:
import pandas as pd
a=[1,3,5,7]
myvar=pd.Series(a)
index=["x","y","z"]
print(myvar)

0    1
1    3
2    5
3    7
dtype: int64


In [ ]:
import pandas as pd
calories = {"day1": 420,"day2": 380,"days3": 390}
myvar = pd.Series(calories)
print(myvar)


day1     420
day2     380
days3    390
dtype: int64


In [ ]:
import pandas as pd
memories = {"day1": 480, "day2": 680, "day3": 360}
myvar = pd.Series(memories,
index=["day1","day2"])
print(myvar)

day1    480
day2    680
dtype: int64


**dataframes**

In [ ]:
import pandas as pd
data = {
    "calories":[420,360,450],
    "period": [50,60,80]
}
myvar = pd.DataFrame(data)
print(myvar)

   calories  period
0       420      50
1       360      60
2       450      80


In [ ]:
sharktank = pd.read_csv("/content/ShartankIndiaAllPitches.csv")

In [ ]:
sharktank.shape

(117, 13)